version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 527165097816.dkr.ecr.ap-south-1.amazonaws.com
      - IMAGE_URI=527165097816.dkr.ecr.ap-south-1.amazonaws.com/demo-app:latest

  build:
    commands:
      - echo "Building Spring Boot application..."
      - cd springboot/ms-demo-service
      - chmod +x gradlew
      - ./gradlew bootJar
      - cd ../..
      - echo "Building Docker image..."
      - docker build -t demo-app -f ecs-app/Dockerfile .
      - docker tag demo-app:latest $IMAGE_URI

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $IMAGE_URI
      - printf '{"ImageURI":"%s"}' $IMAGE_URI > imageDetail.json

artifacts:
  files:
    - imageDetail.json